### ISSUE TITLE
Action inputs not recognized

### ISSUE THREAD

**Issue by brbrr** [afiore/action-allure-report#1]
Hi. Thanks for working on this!

I started playing with this action, and I noticed that action inputs not really recognized. 

```
    - name: Allure report
      uses: afiore/action-allure-report@v0.1.0
      with:
        # Allure test result data dir
        results-dir: results # default is allure-results
        # Allure report target dir
        report-dir: docs # default is allure-report
        
```

the output folder is still the default `allure-report` 

https://github.com/brbrr/test-dashboard-pages/runs/573375634?check_suite_focus=true#step:6:1
